### ISSUE TITLE
Cannot publish solution in dynamics 365 v9

### ISSUE THREAD

**Issue by bennyboy23** [scottdurow/RibbonWorkbench#25]
Hi,
I have attempted to publish a change via the ribbonworkbench in XRMtoolbox.
All I changed was to hide 2 buttons and edit the label of another.
I received an error after it got 34% through the import process.
This was in a dynamics 365 v9 environment.

> Import Failed : Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.osf, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: NewLabelDetail: 
<osf xmlns:i="http://www.w3.org/2001/XMLSchema-instance&quot; xmlns="http://schemas.microsoft.com/xrm/2011/Contracts"> 
<ActivityId>19411153-a9ce-4e56-94fd-748cb2a6b1b8</ActivityId> 
<ErrorCode>-2147220989</ErrorCode> 
<ErrorDetails xmlns:d2p1=""> 
<key> 
<d2p1:key>0</d2p1:key> 
<d2p1:value i:type="d4p1:string">System.ArgumentNullException: Value cannot be null. 
Parameter name: NewLabel</d2p1:value> 
</key> 
</ErrorDetails> 
<Message>NewLabel</Message> 
<Timestamp>2017-12-04T14:45:42.4682531Z</Timestamp> 
<ExceptionRetriable>false</ExceptionRetriable> 
<ExceptionSource i:nil="true" /> 
<InnerFault> 
<ActivityId>19411153-a9ce-4e56-94fd-748cb2a6b1b8</ActivityId> 
<ErrorCode>-2147220989</ErrorCode> 
<ErrorDetails xmlns:d3p1="" /> 
<Message>NewLabel</Message> 
<Timestamp>2017-12-04T14:45:42.4682531Z</Timestamp> 
<ExceptionRetriable>false</ExceptionRetriable> 
<ExceptionSource i:nil="true" /> 
<InnerFault> 
<ActivityId>19411153-a9ce-4e56-94fd-748cb2a6b1b8</ActivityId> 
<ErrorCode>-2147220970</ErrorCode> 
<ErrorDetails xmlns:d4p1="" /> 
<Message>System.ArgumentNullException: Value cannot be null. 
Parameter name: NewLabel</Message> 
<Timestamp>2017-12-04T14:45:42.4682531Z</Timestamp> 
<ExceptionRetriable>false</ExceptionRetriable> 
<ExceptionSource i:nil="true" /> 
<InnerFault i:nil="true" /> 
<OriginalException i:nil="true" /> 
<TraceText i:nil="true" /> 
</InnerFault> 
<OriginalException i:nil="true" /> 
<TraceText i:nil="true" /> 
</InnerFault> 
<OriginalException i:nil="true" /> 
<TraceText i:nil="true" /> 
</osf> 
at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, CorrelationToken correlationToken, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, ExecutionContext executionContext) 
at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, CorrelationToken correlationToken, CallerOriginToken callerOriginToken, WebServiceType serviceType) 
at Microsoft.Crm.Extensibility.InprocessServiceProxy.ExecuteCore(OrganizationRequest request) 
at Microsoft.Crm.Asynchronous.ExecuteSdkMessageOperation.InternalExecute(AsyncEvent asyncEvent)
Stack Trace: 
Error: 
at ClientUI.ViewModel.EditCommandBarsVM.queryImport (:61833/WebResources/js/ClientUI.js:19555:1442) 
at Anonymous function (:61833/WebResources/js/ClientUI.js:19556:1)

> 
Any advice?

Thanks,
Ben

**Comment by bennyboy23** [comment]
This may be the result of having too many entities within a solution.
There were 13 and this was also into a sandbox instance which is limited also.
By reducing the number of entities, I have now been able to publish the changes.
